### ISSUE TITLE
[Bug]: jaeger-ui seems to require Python since the last release (ARM64)

### ISSUE THREAD

**Issue by aoterolorenzo** [jaegertracing/jaeger-ui#1048]
### What happened?

Using a slim base container with Node + Golang (already used successfully to complile the last Jaeger version), results in the following error when running an `npm install` over the `jaeger-ui`:

```
npm ERR! code 1
npm ERR! path /jaeger-ui/node_modules/@parcel/watcher
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@16.16.0 | linux | arm64
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/jaeger-ui/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/jaeger-ui/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/jaeger-ui/node_modules/node-gyp/lib/find-python.js:202:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/jaeger-ui/node_modules/node-gyp/lib/find-python.js:294:16)
npm ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Linux 5.10.124-linuxkit
npm ERR! gyp ERR! command "/opt/b/node-v16.16.0-linux-arm64/bin/node" "/jaeger-ui/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /jaeger-ui/node_modules/@parcel/watcher
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok
```

### Steps to reproduce

Use a slim base container without Python, clone the UI and try to `npm install`. I use an internal one but it should be reproduced with bitnami's minideb container for example:

`docker run -it --rm bitnami/minideb bash`

### Expected behavior

Python is not a dependency for the Jaeger UI

### Operating system

Debian image (arm64 to be specific, ~~but happening also in  others machines amd64~~)

**Comment by aoterolorenzo** [comment]
I'm not fully aware that it is not intentional so feel free to discard the issue if proceed. I wanted just to report in case it doesn't.

**Comment by aoterolorenzo** [comment]
It doesn't happen in non ARM64 machines/images!
