### ISSUE TITLE
[Bug] Unstable test in jaeger-ui/src/api/jaeger.test.js

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1846]
This test recently failed and then succeeded on the rerun. From the stack trace it looks like an issue with randomly generated timestamps.

https://github.com/jaegertracing/jaeger-ui/actions/runs/6406079597/job/17389965009?pr=1845#step:5:65

```
FAIL  src/api/jaeger.test.js
  ● Test suite failed to run

    RangeError: Chance: Min cannot be greater than Max.

      148 |       references: [],
      149 |       startTime,
    > 150 |       duration: chance.integer({ min: 1, max: traceEndTime - startTime }),
          |                        ^
      151 |       tags: chance.tags(),
      152 |       logs: [],
      153 |     };

      at testRange (../../node_modules/chance/chance.js:98:19)
      at Chance.testRange [as integer] (../../node_modules/chance/chance.js:281:9)
      at Chance.integer [as span] (src/demo/trace-generators.js:150:24)
      at Chance.apply [as n] (../../node_modules/chance/chance.js:634:25)
      at Chance.n [as trace] (src/demo/trace-generators.js:106:24)
      at Chance.apply [as n] (../../node_modules/chance/chance.js:634:25)
      at Chance.n [as traces] (src/demo/trace-generators.js:163:19)
      at traces (src/api/jaeger.test.js:117:42)
      at Object.describe (src/api/jaeger.test.js:116:1)
```

**Comment by MeenuyD** [comment]
Hello @yurishkuro I would like to work on this issue can you assign it to me?
