### ISSUE TITLE
[Bug]: dependabot updates are broken

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1964]
### What happened?

Dependabot is supposed to create new PRs for stale dependencies. I kicked it off manually twice, it failed both times:

Errored with the message "Dependabot encountered an unknown error"
No PRs affected 4 hours ago [view logs](https://github.com/jaegertracing/jaeger-ui/network/updates/748031826)

The failure happens here:
```
Updating @types/react from 18.2.33 to 18.2.37
```

Maybe we can resolve it by doing a manual upgrade. This error is preventing creation of other PRs, like `jest` upgrade that was failing to rebase yesterday.

### Steps to reproduce

There's probably a way to run dependabot locally, but I only ran it via GitHub

### Expected behavior

create PRs for stale deps

### Relevant log output

```shell
Errored with the message "Dependabot encountered an unknown error"

updater | 2023/11/10 12:36:09 INFO <job_748031826> Updating @types/react from 18.2.33 to 18.2.37
  proxy | 2023/11/10 12:36:11 [580] GET https://registry.yarnpkg.com:443/@types%2freact
  proxy | 2023/11/10 12:36:12 [580] 200 https://registry.yarnpkg.com:443/@types%2freact
  proxy | 2023/11/10 12:36:13 [582] GET https://registry.yarnpkg.com:443/lodash
  proxy | 2023/11/10 12:36:13 [582] 200 https://registry.yarnpkg.com:443/lodash
updater | 2023/11/10 12:36:13 INFO <job_748031826> Sending event feebdcd70abe4bebbf035eb56cfe4077 to Sentry
  proxy | 2023/11/10 12:36:14 [584] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/11/10 12:36:14 [584] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/10 12:36:14 ERROR <job_748031826> Error processing @types/react (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
updater | 2023/11/10 12:36:14 ERROR <job_748031826> No files were updated!
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:47:in `updated_dependency_files'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:87:in `generate_dependency_files'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:95:in `create_change_for'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:56:in `block in compile_all_dependency_changes_for'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:114:in `run_update_for'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:96:in `block in run_grouped_dependency_updates'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `each'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `run_grouped_dependency_updates'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:45:in `perform'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/10 12:36:14 ERROR <job_748031826> bin/update_files.rb:24:in `<main>'
```

**Comment by yurishkuro** [comment]
cc @anshgoyalevil

**Comment by anshgoyalevil** [comment]
@yurishkuro I think we would have to add react and @types/react to ignore the list of depandabot. Otherwise depandabot would try to upgrade it but would fail to do so, because of resolution.

**Comment by yurishkuro** [comment]
The dependabot run succeeded, but still it did not create a PR for jest upgrade

**Comment by anshgoyalevil** [comment]
The may be because we yesterday closed one of its PRs where it was stuck at jest upgrade. Now depandabot would create PR for the next version available. (Just an assumption)

**Comment by yurishkuro** [comment]
> The may be because we yesterday closed one of its PRs where it was stuck at jest upgrade. Now depandabot would create PR for the next version available. (Just an assumption)

that's exactly what I am hoping to get, but I am not seeing this. Jest is now 29.7, we use 29.6.x, but I am not seeing DB putting up a PR.

**Comment by anshgoyalevil** [comment]
I think that depends upon the upstream jest version at which we closed the PR and not upon the version we are at.

So for example, yesterday, jest was a 29.7 in upstream, but we closed it. So when jest would be at 29.8 in upstream, maybe we would get a PR

**Comment by yurishkuro** [comment]
I don't believe it's how DB works - it creates a PR for an exact version and if you close it it marks only that specific version as "ignore". DB itself even cannot re-bump the version (like 29.6.1 -> 29.6.2) in the same PR, it will always close it and create a new one, because I think somewhere internally it keeps a mapping `PR# -> dep/version`. So because I closed 29.6.x should not stop it from doing 29.7

**Comment by yurishkuro** [comment]
logs from latest run actually looks like your version of the behavior
```
updater | 2023/11/10 20:19:38 INFO <job_748226700> Ignored versions:
updater | 2023/11/10 20:19:38 INFO <job_748226700>   < 30, > 29.4.2 - from @dependabot ignore command
  proxy | 2023/11/10 20:19:38 [068] GET https://registry.yarnpkg.com:443/jest
  proxy | 2023/11/10 20:19:38 [068] 200 https://registry.yarnpkg.com:443/jest
updater | 2023/11/10 20:19:38 INFO <job_748226700> All updates for jest were ignored
```
I will try to convince dbot to redo #1240 again.

**Comment by yurishkuro** [comment]
no help, it still treats it as ignored. There is an open issue for dbot https://github.com/dependabot/dependabot-core/issues/6489

**Comment by yurishkuro** [comment]
```
updater | 2023/11/10 22:05:25 INFO <job_748284208> Checking if jest 29.6.2 needs updating
updater | 2023/11/10 22:05:25 INFO <job_748284208> Ignored versions:
updater | 2023/11/10 22:05:25 INFO <job_748284208>   < 30, > 29.4.2 - from @dependabot ignore command
updater | 2023/11/10 22:05:25 INFO <job_748284208>   >= 29.4.a, < 29.5 - from @dependabot ignore command
  proxy | 2023/11/10 22:05:25 [068] GET https://registry.yarnpkg.com:443/jest
  proxy | 2023/11/10 22:05:25 [068] 200 https://registry.yarnpkg.com:443/jest
updater | 2023/11/10 22:05:25 INFO <job_748284208> All updates for jest were ignored
```
somehow dbot got into its head that `< 30, > 29.4.2` should be ignored, even though we never said so in that PR.

**Comment by yurishkuro** [comment]
doh, I did it in #1201

**Comment by yurishkuro** [comment]
🎉 https://github.com/jaegertracing/jaeger-ui/pull/1969

**Comment by anshgoyalevil** [comment]
Finally you did it 🎉🎉🎉
