### ISSUE TITLE
yarn build failed

### ISSUE THREAD

**Issue by meilihao** [jaegertracing/jaeger-ui#245]
## env
os: deepin 15.7
node:  v6.14.4
jaeger-ui: git@d148dc5

## log
```
$ yarn
yarn install v1.9.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-airbnb@15.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
warning " > eslint-config-react-app@2.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
warning " > glow@1.2.2" has incorrect peer dependency "flow-bin@^0.63.1".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > @jaegertracing/plexus@0.0.1-dev.3" has unmet peer dependency "react@16.x".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-dimensions@1.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-dimensions@1.3.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-router-dom@4.1.2" has incorrect peer dependency "react@^15".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-router-redux@5.0.0-alpha.6" has incorrect peer dependency "react@^15".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-vis@1.7.2" has incorrect peer dependency "react@0.14.x - 15.x".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-vis-force@0.3.1" has incorrect peer dependency "react@0.14.x - 15.x".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-vis-force@0.3.1" has incorrect peer dependency "react-dom@0.14.x - 15.x".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > recompose@0.25.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-test-renderer@15.6.1" has incorrect peer dependency "react@^15.6.1".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > antd > rc-editor-mention@1.1.1" has unmet peer dependency "immutable@~3.7.4".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-router-dom > react-router@4.1.2" has incorrect peer dependency "react@^15".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > react-app-rewire-less > less-loader@4.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > @jaegertracing/plexus > nwb > babel-plugin-inferno@3.3.1" has unmet peer dependency "inferno@3.x".
warning "workspace-aggregator-633a3f56-6189-4b09-b02f-b1113424f922 > jaeger-ui > antd > react-slick > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
[4/4] Building fresh packages...
$ lerna run --stream --sort prepublishOnly
lerna info version 2.10.2
lerna info versioning independent
@jaegertracing/plexus: yarn run v1.9.4
@jaegertracing/plexus: $ nwb build-react-component --no-demo
@jaegertracing/plexus: ✔ Cleaning module
@jaegertracing/plexus: ✔ Creating ES5 build
@jaegertracing/plexus: Failed to compile with 1 error.
@jaegertracing/plexus:  ERROR  in ./src/LayoutManager/layout.worker.js
@jaegertracing/plexus: Module build failed: TypeError: Cannot read property 'thisCompilation' of undefined
@jaegertracing/plexus:     at WebWorkerTemplatePlugin.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/webpack/lib/webworker/WebWorkerTemplatePlugin.js:13:17)
@jaegertracing/plexus:     at Compiler.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:375:16)
@jaegertracing/plexus:     at Object.pitch (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/packages/plexus/node_modules/worker-loader/dist/index.js:87:19)
@jaegertracing/plexus:  @ ./src/LayoutManager/Coordinator.js 14:43-86
@jaegertracing/plexus:  @ ./src/LayoutManager/LayoutManager.js
@jaegertracing/plexus:  @ ./src/LayoutManager/index.js
@jaegertracing/plexus:  @ ./src/index.js
@jaegertracing/plexus:  @ multi ./src/index.js
@jaegertracing/plexus: ✖ Creating UMD builds
@jaegertracing/plexus: Error running command: Build failed with errors.
@jaegertracing/plexus: Error: Build failed with errors.\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/lib/webpackBuild.js:76:17\n    at emitRecords.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:265:13)\n    at Compiler.emitRecords (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:371:38)\n    at emitAssets.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:258:10)\n    at applyPluginsAsyncSeries1.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:364:12)\n    at next (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:218:11)\n    at Compiler.compiler.plugin (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)\n    at Compiler.applyPluginsAsyncSeries1 (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:222:13)\n    at Compiler.afterEmit (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:361:9)\n    at require.forEach.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:350:15)\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:473:16\n    at iteratorCallback (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:1050:13)\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:958:16\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/graceful-fs/graceful-fs.js:43:10\n    at FSReqWrap.oncomplete (fs.js:123:15)
@jaegertracing/plexus: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@jaegertracing/plexus: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run prepublishOnly
lerna ERR! ✔ Cleaning module
lerna ERR! ✔ Creating ES5 build
lerna ERR! ✖ Creating UMD builds
lerna ERR! Error running command: Build failed with errors.
lerna ERR! Error: Build failed with errors.
lerna ERR!     at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/lib/webpackBuild.js:76:17
lerna ERR!     at emitRecords.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:265:13)
lerna ERR!     at Compiler.emitRecords (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:371:38)
lerna ERR!     at emitAssets.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:258:10)
lerna ERR!     at applyPluginsAsyncSeries1.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:364:12)
lerna ERR!     at next (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:218:11)
lerna ERR!     at Compiler.compiler.plugin (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
lerna ERR!     at Compiler.applyPluginsAsyncSeries1 (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:222:13)
lerna ERR!     at Compiler.afterEmit (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:361:9)
lerna ERR!     at require.forEach.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:350:15)
lerna ERR!     at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:473:16
lerna ERR!     at iteratorCallback (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:1050:13)
lerna ERR!     at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:958:16
lerna ERR!     at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/graceful-fs/graceful-fs.js:43:10
lerna ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
lerna ERR! error Command failed with exit code 1.
lerna ERR! 
lerna ERR! yarn run v1.9.4
lerna ERR! $ nwb build-react-component --no-demo
lerna ERR! Failed to compile with 1 error.
lerna ERR! 
lerna ERR!  ERROR  in ./src/LayoutManager/layout.worker.js
lerna ERR! Module build failed: TypeError: Cannot read property 'thisCompilation' of undefined
lerna ERR!     at WebWorkerTemplatePlugin.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/webpack/lib/webworker/WebWorkerTemplatePlugin.js:13:17)
lerna ERR!     at Compiler.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:375:16)
lerna ERR!     at Object.pitch (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/packages/plexus/node_modules/worker-loader/dist/index.js:87:19)
lerna ERR!  @ ./src/LayoutManager/Coordinator.js 14:43-86
lerna ERR!  @ ./src/LayoutManager/LayoutManager.js
lerna ERR!  @ ./src/LayoutManager/index.js
lerna ERR!  @ ./src/index.js
lerna ERR!  @ multi ./src/index.js
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/execa/index.js:236:11)
{ Error: Command failed: yarn run prepublishOnly
✔ Cleaning module
✔ Creating ES5 build
✖ Creating UMD builds
Error running command: Build failed with errors.
Error: Build failed with errors.
    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/lib/webpackBuild.js:76:17
    at emitRecords.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:1050:13)
    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:958:16
    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.

yarn run v1.9.4
$ nwb build-react-component --no-demo
Failed to compile with 1 error.

 ERROR  in ./src/LayoutManager/layout.worker.js
Module build failed: TypeError: Cannot read property 'thisCompilation' of undefined
    at WebWorkerTemplatePlugin.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/webpack/lib/webworker/WebWorkerTemplatePlugin.js:13:17)
    at Compiler.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:375:16)
    at Object.pitch (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/packages/plexus/node_modules/worker-loader/dist/index.js:87:19)
 @ ./src/LayoutManager/Coordinator.js 14:43-86
 @ ./src/LayoutManager/LayoutManager.js
 @ ./src/LayoutManager/index.js
 @ ./src/index.js
 @ multi ./src/index.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  code: 1,
  killed: false,
  stdout: 'yarn run v1.9.4\n$ nwb build-react-component --no-demo\nFailed to compile with 1 error.\n\n ERROR  in ./src/LayoutManager/layout.worker.js\nModule build failed: TypeError: Cannot read property \'thisCompilation\' of undefined\n    at WebWorkerTemplatePlugin.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/webpack/lib/webworker/WebWorkerTemplatePlugin.js:13:17)\n    at Compiler.apply (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:375:16)\n    at Object.pitch (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/packages/plexus/node_modules/worker-loader/dist/index.js:87:19)\n @ ./src/LayoutManager/Coordinator.js 14:43-86\n @ ./src/LayoutManager/LayoutManager.js\n @ ./src/LayoutManager/index.js\n @ ./src/index.js\n @ multi ./src/index.js\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: '✔ Cleaning module\n✔ Creating ES5 build\n✖ Creating UMD builds\nError running command: Build failed with errors.\nError: Build failed with errors.\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/lib/webpackBuild.js:76:17\n    at emitRecords.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:265:13)\n    at Compiler.emitRecords (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:371:38)\n    at emitAssets.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:258:10)\n    at applyPluginsAsyncSeries1.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:364:12)\n    at next (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:218:11)\n    at Compiler.compiler.plugin (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)\n    at Compiler.applyPluginsAsyncSeries1 (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/tapable/lib/Tapable.js:222:13)\n    at Compiler.afterEmit (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:361:9)\n    at require.forEach.err (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/nwb/node_modules/webpack/lib/Compiler.js:350:15)\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:473:16\n    at iteratorCallback (/home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:1050:13)\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/async/dist/async.js:958:16\n    at /home/chen/git/go/src/github.com/jaegertracing/jaeger-ui/node_modules/graceful-fs/graceful-fs.js:43:10\n    at FSReqWrap.oncomplete (fs.js:123:15)\nerror Command failed with exit code 1.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run prepublishOnly',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I also used other versions of the node: v8.11.4/v10.10.0, got the similar error.

**Comment by tiffon** [comment]
@meilihao, thanks for reporting this. Apologies for the slow response!

I'm not able to reproduce this on a fresh checkout of the repo (the output is at the end of this comment).

I noticed there's an interesting warning at the top of the output you included:

> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

Do you know which file that's referring to? There isn't a package-lock.json file in the repo.

Also, in your installation (node_modules) is the file where the error occurs (`node_modules/webpack/lib/webworker/WebWorkerTemplatePlugin.js`) the same as what I've inlined below?

```
/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
"use strict";

const WebWorkerMainTemplatePlugin = require("./WebWorkerMainTemplatePlugin");
const WebWorkerChunkTemplatePlugin = require("./WebWorkerChunkTemplatePlugin");
const WebWorkerHotUpdateChunkTemplatePlugin = require("./WebWorkerHotUpdateChunkTemplatePlugin");

class WebWorkerTemplatePlugin {
	apply(compiler) {
		compiler.plugin("this-compilation", compilation => {
			compilation.mainTemplate.apply(new WebWorkerMainTemplatePlugin());
			compilation.chunkTemplate.apply(new WebWorkerChunkTemplatePlugin());
			compilation.hotUpdateChunkTemplate.apply(new WebWorkerHotUpdateChunkTemplatePlugin());
		});
	}
}
module.exports = WebWorkerTemplatePlugin;
```

### yarn install output

```
$ git rev-parse --short HEAD
d148dc5

$ node -v
v6.14.3

$ yarn -v
1.9.4

$ yarn
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-airbnb@15.1.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
warning " > eslint-config-react-app@2.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@^5.1.1".
warning " > glow@1.2.2" has incorrect peer dependency "flow-bin@^0.63.1".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > @jaegertracing/plexus@0.0.1-dev.3" has unmet peer dependency "react@16.x".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-dimensions@1.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-dimensions@1.3.0" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-router-dom@4.1.2" has incorrect peer dependency "react@^15".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-router-redux@5.0.0-alpha.6" has incorrect peer dependency "react@^15".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-vis@1.7.2" has incorrect peer dependency "react@0.14.x - 15.x".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-vis-force@0.3.1" has incorrect peer dependency "react@0.14.x - 15.x".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-vis-force@0.3.1" has incorrect peer dependency "react-dom@0.14.x - 15.x".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > recompose@0.25.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-test-renderer@15.6.1" has incorrect peer dependency "react@^15.6.1".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > @jaegertracing/plexus > worker-loader@1.1.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > antd > rc-editor-mention@1.1.1" has unmet peer dependency "immutable@~3.7.4".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-router-dom > react-router@4.1.2" has incorrect peer dependency "react@^15".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > react-app-rewire-less > less-loader@4.0.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > @jaegertracing/plexus > nwb > babel-plugin-inferno@3.3.1" has unmet peer dependency "inferno@3.x".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > @jaegertracing/plexus > worker-loader > schema-utils@0.4.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-f8dab16b-67ea-466b-a7c9-58752dda72da > jaeger-ui > antd > react-slick > slick-carousel@1.8.1" has unmet peer dependency "jquery@>=1.8.0".
[4/4] 📃  Building fresh packages...
$ lerna run --stream --sort prepublishOnly
lerna info version 2.10.2
lerna info versioning independent
@jaegertracing/plexus: yarn run v1.9.4
@jaegertracing/plexus: $ nwb build-react-component --no-demo
@jaegertracing/plexus: ✔ Creating ES5 build
@jaegertracing/plexus: ✔ Creating UMD builds
@jaegertracing/plexus: File sizes after gzip:
@jaegertracing/plexus:   umd/@jaegertracing/plexus.js      623.27 KB
@jaegertracing/plexus:   umd/@jaegertracing/plexus.min.js  583.36 KB
@jaegertracing/plexus: Done in 59.64s.
lerna success run Ran npm script 'prepublishOnly' in packages:
lerna success - @jaegertracing/plexus
✨  Done in 108.89s.
```

**Comment by clyang82** [comment]
@meilihao You can read the README and find that the output is in `packages/jaeger-ui/build` instead of `build`.
