### ISSUE TITLE
[Deps] Upgrade history package to 5.x

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#2531]

**Comment by jayesh9747** [comment]
@yurishkuro  i want to work on this issue can you assign me ?

**Comment by jayesh9747** [comment]
@yurishkuro  can you describe in details like what should excalty  waht outcome you want ?

**Comment by yurishkuro** [comment]
The desired outcome is that we don't have a stale dependency - we either upgrade to the latest version or if the dependency is deprecated altogether we find something else that is maintained.

**Comment by jayesh9747** [comment]
@yurishkuro, after updating the history version to 5.x, how can I check if it is compatible with this repository and passes all the tests?

**Comment by yurishkuro** [comment]
You run the tests, npm run test, npm run lint.

We already know that it's not compatible, the automated upgrade is failing CI.

**Comment by jayesh9747** [comment]
@yurishkuro 

As I searched on Google to find an alternative to History.js, I discovered that no direct alternatives are available. Therefore, I prefer to resolve the test cases that were filed instead.

![Image](https://github.com/user-attachments/assets/1d673b3e-8aaa-4927-bdb3-c7398c3bf24a)

**Comment by yurishkuro** [comment]
If it is unmaintained it's not enough to fix the tests, we need to actively get rid of it.

**Comment by yurishkuro** [comment]
But fixing the test can be a first step.

**Comment by jayesh9747** [comment]
@yurishkuro  sure , will PR very soon.

**Comment by manzil-infinity180** [comment]
@yurishkuro 

I upgraded to 5.X and tested it, two test cases failing one for the `history.length` and other one is for` toMatchSnapshot()`

```bash
 console.log
      {
        "index": 1,
        "action": "PUSH",
        "location": {
          "pathname": "/trace/MOCK-TRACE-ID",
          "search": "",
          "hash": "",
          "state": null,
          "key": "8kaa6msa"
        }
      }

      at Object.log (src/components/App/TraceIDSearchInput.test.js:50:13)

    console.log
      {
        "index": 0,
        "action": "POP",
        "location": {
          "pathname": "/",
          "search": "",
          "hash": "",
          "state": null,
          "key": "jxeeyogw"
        }
      }

      at Object.log (src/components/App/TraceIDSearchInput.test.js:57:13)

  ● <TraceIDSearchInput /> › does not push to history on falsy input value

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: undefined

      57 |     console.log(JSON.stringify(history, null, 2));
      58 |     expect(history.action).toEqual('POP');
    > 59 |     expect(history.length).toEqual(1);
         |                            ^
      60 |   });
      61 | });
      62 |

      at Object.toEqual (src/components/App/TraceIDSearchInput.test.js:59:28)

(node:17363) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 FAIL  src/components/App/index.test.js
  ● JaegerUIApp › does not explode

    expect(received).toMatchSnapshot()

    Snapshot name: `JaegerUIApp does not explode 1`

    - Snapshot  - 4
    + Received  + 6


```
 as we clearly see the history.length is undefined so test are failing

**Comment by Parship999** [comment]
https://www.npmjs.com/package/history
https://github.com/remix-run/history/releases

**Comment by Parship999** [comment]
Hey @yurishkuro 
I have upgraded the history package from v4.6.3 to v5.3.0 by the following steps-
1. first installed the new version
2. changed the import statements from `history/createMemoryHistory` to `import { createMemoryHistory } from 'history'`
3. updated the typescript types to match the changes in location
4. Fixed undefined `history.length`

But after this a problem arised, the ui loaded fine but the buttons like search, compare stopped working properly. After each click, I have to refresh the page to get the response, then I found the issues were because of the react router v5 was working properly only with history v4 then history v5 has many API changes. The main issue was how the history object was interacting with React router and redux.
To solve this problem, I created a polyfill in `configure-store.js`, it solves the API differnces problem between history v4 and v5. But the polyfill would need to be removed during the react-router-dom upgradation. For now it's a suitable solution. I have done both the lint and test run, both passed.
Can you please verify the process? then I will raise a PR.

**Comment by anshgoyalevil** [comment]
`history` is ultimately not required.

We are currently on `react-router-dom` v5, and it indeed uses `history` v4 internally, but there's more to the story.

`react-router-dom` v6 uses `history` v5 internally, but it doesn't allow or expose direct access to the `history` object. iirc, there are some tests in jaeger-ui that use the `history` object directly.
The replacement for the `history` object is the new `useNavigate` hook.

`react-router-dom` v7 doesn't use `history` at all. It has its own navigation mechanism. Again, it provides `useNavigate` hook to navigate to the other pages instead of using `history.push` thing to navigate as in the current (v5) of `react-router-dom`

The way I see it, you would ultimately have to remove the `history` package in the future because neither `react-router-dom` v6 nor v7 recommends it.

The steps towards upgrading the project as a whole would be to
- First shift to functional components in place of class components. 
- After that is done, try removing the instances of the `history` package and use `useNavigate` hook (you can now use hooks because functional components are allowed to do that)
- The project already uses `react-router-dom` [v5 compat v6,](https://github.com/jaegertracing/jaeger-ui/blob/main/packages/jaeger-ui/package.json#L81C6-L81C32) so you can directly use `react-router-dom` v6 APIs without breaking the whole project. Aim for 1 file/router at a time in one PR.

I don't remember Redux interfering with all these router dependencies, or if is, the problem would be fixed once `history` be removed, and `react-router-dom` be upgraded to v6 and eventually v7

**Comment by vishvamsinh28** [comment]
Since we’re planning to move to React 19 soon, I think it's good to switch over to useNavigate. It’s more in line with modern React (hooks + functional components), avoids old history API quirks, and will save us from compatibility headaches down the road. The refactor might take a bit of work, but the long-term benefits in simplicity and maintainability are worth it.

@yurishkuro @anshgoyalevil

**Comment by Parship999** [comment]
@yurishkuro @vishvamsinh28 @anshgoyalevil 
Thank you all for the valuable feedbacks. After reviewing the feedbacks, I think we need to clarify 2 options:
Current senario is we have history v4, react router dom v5 and jaeger-ui uses redux first history v5 for redux router integration.
Option 1 is upgrading by my approach(using polyfill) that also maintains existing redux routing integration.
Option 2 is switching to useNavigate which require huge changes throughout the codebase but it's future proof and algins with the React 19 upgradation.

**Comment by ghost** [comment]
@yurishkuro 
As discussed in the above comments, the history package is no longer required. React Router v6 uses history internally but doesn’t expose it; React Router v7 doesn’t use it at all. The modern way to navigate is with the `useNavigate` hook instead of `history.push`.

To upgrade the project:
1. Convert class components to functional components. (#2610): this issue doesn't need to be addressed 100%, we can do the conversion only for files that use history.
2. Replace all history usage with `useNavigate`.
3. Do this gradually - one file/router per PR - since the project uses `react-router-dom v5 compat v6`, so we can directly use `react-router-dom v6` APIs.

Eventually, history can be removed entirely, because neither react-router-dom v6 nor v7 recommends it.

#### Files using `history`:

```
/packages/jaeger-ui/src/utils/useHistory.tsx
/packages/jaeger-ui/src/utils/withRouteProps.tsx
/packages/jaeger-ui/src/utils/configure-store.js
/packages/jaeger-ui/src/utils/update-ui-find.tsx
/packages/jaeger-ui/src/components/App/TraceIDSearchInput.tsx
/packages/jaeger-ui/src/components/TracePage/index.tsx
/packages/jaeger-ui/src/components/SearchTracePage/index.jsx
/packages/jaeger-ui/src/components/TraceDiff/TraceDiff.tsx
/packages/jaeger-ui/src/components/DeepDependencies/index.tsx
/packages/jaeger-ui/src/components/QualityMetrics/index.tsx
/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.tsx
/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItemTitle.tsx
/packages/jaeger-ui/src/components/DeepDependencies/traces.tsx
/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx
/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx
/packages/jaeger-ui/src/components/common/UiFindInput.tsx
/packages/jaeger-ui/src/types/index.tsx
/packages/jaeger-ui/src/components/App/index.test.js
/packages/jaeger-ui/src/components/App/TraceIDSearchInput.test.js
/packages/jaeger-ui/src/components/TraceDiff/TraceDiff.test.js
/packages/jaeger-ui/src/components/DeepDependencies/index.test.js
/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItemTitle.test.js
/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.test.js
/packages/jaeger-ui/src/components/TracePage/index.test.js
/packages/jaeger-ui/src/components/SearchTracePage/index.test.js
/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/index.test.js
/packages/jaeger-ui/src/components/QualityMetrics/index.test.js
/packages/jaeger-ui/src/components/TracePage/ArchiveNotifier/duck.test.js
/packages/jaeger-ui/src/components/common/UiFindInput.test.js
/packages/jaeger-ui/src/utils/withRouteProps.test.js
/packages/jaeger-ui/src/utils/configure-store.test.js
/packages/jaeger-ui/src/utils/update-ui-find.test.js
/packages/jaeger-ui/src/utils/useHistory.test.js
/packages/jaeger-ui/src/utils/tracking/ga.test.js
/packages/jaeger-ui/src/middlewares/index.js
```
**Few files are there just use imports only**

As of now, I have found the above files that use history. If I missed any or found while working through the codebase, I will add them here.

**Comment by ghost** [comment]
### Files using `history` (Updated):
```
/packages/jaeger-ui/src/utils/withRouteProps.tsx
/packages/jaeger-ui/src/utils/configure-store.js
/packages/jaeger-ui/src/utils/update-ui-find.tsx
/packages/jaeger-ui/src/components/TracePage/index.tsx
/packages/jaeger-ui/src/components/DeepDependencies/index.tsx
/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.tsx
/packages/jaeger-ui/src/components/SearchTracePage/SearchResults/ResultItem.tsx
/packages/jaeger-ui/src/types/index.tsx
/packages/jaeger-ui/src/components/App/TraceIDSearchInput.test.js
/packages/jaeger-ui/src/components/TracePage/TraceTimelineViewer/VirtualizedTraceView.test.js
/packages/jaeger-ui/src/components/TracePage/index.test.js
/packages/jaeger-ui/src/components/TracePage/ArchiveNotifier/duck.test.js
/packages/jaeger-ui/src/utils/withRouteProps.test.js
/packages/jaeger-ui/src/utils/configure-store.test.js
/packages/jaeger-ui/src/utils/update-ui-find.test.js
```

**Comment by ghost** [comment]
@yurishkuro we can't remove `history` package directly. We will need to remove `redux-first-history` too. It's a wrapper around the `history` package - it takes a history instance as input and syncs it with Redux. Without `history`, `redux-first-history` can't function.
Means if we remove history, we have to remove `redux-first-history` also and use React router directly.

**Comment by yurishkuro** [comment]
@Parship12 agreed. Looks like the usage of that is pretty minimal?

```
$ rg redux-first-history
packages/jaeger-ui/src/middlewares/index.ts
5:import { replace } from 'redux-first-history';

packages/jaeger-ui/src/utils/configure-store.ts
5:import { createReduxHistoryContext } from 'redux-first-history';
```

**Comment by ghost** [comment]
@yurishkuro yes, only 2 files import it directly but indirectly through `state.router` in redux which files read from, plus I have seen `withRouteProps` that wraps in some components.
